apiVersion: v1
kind: Service
metadata:
  name: assignment1
  labels:
    application: assignment1
  annotations:
    auth.istio.io/8080: NONE
spec:
  ports:
  - name: http
    port: 8080
  type: NodePort
  selector:
    application: assignment1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: assignment1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: assignment1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: ${dockerImageName}
        imagePullPolicy: Always
        name: assignment1
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: assignment1
spec:
  hostname: ${hostName}
  service:
    name: assignment1
    port: 8080